#!/usr/bin/env python3
"""Minimal, deterministic resume state for one finding (audit finding F-16).

Usage:
    python3 factory/guards/finding_state.py record <ID> key=value [key=value ...]
    python3 factory/guards/finding_state.py show   <ID>
    python3 factory/guards/finding_state.py assess <ID>
    python3 factory/guards/finding_state.py path   <ID>

Exit code 0: the state was recorded / shown / assessed.
Exit code 1: an inconsistency that must stop an unattended run
             (AUTONOMY_BLOCKER), or an unusable argument.

## Why this exists

A session can die: the machine sleeps, the process is killed, the context
runs out, a human interrupts. Before this, a fresh agent picking the work up
had no way to establish what had already happened. It could not tell

  - a branch that exists because IT created it from one that exists because
    somebody else did,
  - "not pushed yet" from "pushed, and the remote already has it",
  - "no pull request" from "PR #4 is open" from "PR #4 was merged an hour
    ago",
  - a green CI run for THIS head from a green run for a head two commits ago,
  - a review PASS that still covers the code from one that expired.

so it guessed -- and a guess in this position either redoes destructive work
or, far worse, carries evidence forward onto code that evidence never saw.

## What this is, and deliberately is not

It is a small JSON file per finding under `.factory/state/`, which is
gitignored, plus one assessment command that re-derives the truth from git
and the repository and compares it against what was recorded.

It is NOT a workflow engine, and it is NOT evidence. The authoritative
answers live where they always did: git for branches and heads, GitHub for
pull requests and CI (`gh-query.sh pr-for-branch`, `required-check`),
`factory/reviews/` for review rounds. This file is an index into them, and
every recorded value is re-checked before it is believed.

That is why it is deliberately untracked. Recording it in git would put a
mutable, agent-written file inside the scope hash, so every state update
would invalidate the review it is supposed to help resume -- and it would
dress up a convenience cache as part of the reviewed record.

## The one rule that matters

**Stale evidence is invalid evidence.** If the branch head has moved past the
pushed SHA that CI was green for, `assess` reports `ci_state: stale`, not
`ci_state: current`. If the repository's scope hash has moved past the hash
the latest review round was stamped with, it reports `review_state: stale`.
Resuming must never let a previous run's green result apply to code it never
covered -- that is precisely the F-03 binding, restated for the resume path.
"""
import argparse
import json
import subprocess
import sys
import time
from pathlib import Path

# Same reason as validate-finding.py: importing scope_hash must not leave
# generated bytecode next to the source, because a later `git add -A` would
# track it and move the very hash being measured.
sys.dont_write_bytecode = True

sys.path.insert(0, str(Path(__file__).resolve().parent))
from scope_hash import ScopeHashError, compute_scope_hash  # noqa: E402

DEFAULT_REPO_ROOT = Path(__file__).resolve().parents[2]
STATE_DIR_NAME = ".factory/state"

# The complete, fixed set of recordable keys. An unknown key is rejected
# rather than stored: a typo that silently becomes a new field would produce
# a state file that looks informative and answers nothing.
STATE_KEYS = (
    "base_sha",
    "branch",
    "worktree",
    "pushed_sha",
    "pr_number",
    "ci_head_sha",
    "ci_run",
    "merge_state",
    "note",
)

ALLOWED_MERGE_STATES = ("none", "open", "merged", "closed", "unknown")

REVIEW_RESULT_PREFIX = "Result:"
REVIEW_SCOPE_HASH_PREFIX = "Reviewed Scope Hash:"


class StateError(RuntimeError):
    """The state could not be read, written or assessed."""


def state_path(repo_root, finding_id):
    return Path(repo_root) / STATE_DIR_NAME / f"{finding_id}.json"


def load_state(repo_root, finding_id):
    path = state_path(repo_root, finding_id)
    if not path.is_file():
        return {}
    try:
        data = json.loads(path.read_text(encoding="utf-8"))
    except (OSError, ValueError) as exc:
        raise StateError(f"Zustandsdatei {path} ist nicht lesbar: {exc}") from exc
    if not isinstance(data, dict):
        raise StateError(f"Zustandsdatei {path} enthaelt kein JSON-Objekt.")
    return data


def record_state(repo_root, finding_id, pairs):
    """Idempotent upsert: recording the same value twice changes nothing."""
    state = load_state(repo_root, finding_id)
    for raw in pairs:
        if "=" not in raw:
            raise StateError(f"'{raw}' ist kein key=value-Paar.")
        key, value = raw.split("=", 1)
        key = key.strip()
        value = value.strip()
        if key not in STATE_KEYS:
            raise StateError(
                f"Unbekannter Zustandsschluessel '{key}'. Erlaubt sind: "
                + ", ".join(STATE_KEYS)
            )
        if key == "merge_state" and value not in ALLOWED_MERGE_STATES:
            raise StateError(
                f"merge_state '{value}' ist unbekannt. Erlaubt: "
                + ", ".join(ALLOWED_MERGE_STATES)
            )
        state[key] = value

    state["updated_at"] = time.strftime("%Y-%m-%dT%H:%M:%SZ", time.gmtime())

    path = state_path(repo_root, finding_id)
    path.parent.mkdir(parents=True, exist_ok=True)
    path.write_text(json.dumps(state, indent=2, sort_keys=True) + "\n", encoding="utf-8")
    return state


def _git(repo_root, *args):
    """Run git in repo_root; return (rc, stdout stripped)."""
    try:
        result = subprocess.run(
            ["git", *args], cwd=str(repo_root), capture_output=True, text=True
        )
    except OSError as exc:
        raise StateError(f"git ist nicht ausfuehrbar: {exc}") from exc
    return result.returncode, result.stdout.strip()


def _review_rounds(repo_root, finding_id):
    """[(round_number, path)] sorted ascending."""
    reviews_dir = Path(repo_root) / "factory" / "reviews"
    if not reviews_dir.is_dir():
        return []
    rounds = []
    for path in reviews_dir.glob(f"{finding_id}.round-*.md"):
        stem = path.name[len(f"{finding_id}.round-") : -len(".md")]
        if stem.isdigit():
            rounds.append((int(stem), path))
    return sorted(rounds)


def _read_prefixed(path, prefix):
    for line in path.read_text(encoding="utf-8").splitlines():
        if line.startswith(prefix):
            return line[len(prefix) :].strip()
    return None


def assess(repo_root, finding_id):
    """Return (lines, blocked, blocker_reason) describing the resumable state."""
    repo_root = Path(repo_root).resolve()
    state = load_state(repo_root, finding_id)
    lines = [f"finding: {finding_id}", f"state_file: {state_path(repo_root, finding_id)}"]
    blocked = False
    blocker = None

    if not state:
        lines.append("recorded_state: none")

    branch = state.get("branch")
    lines.append(f"branch: {branch or 'none'}")

    branch_head = None
    if branch:
        rc, out = _git(repo_root, "rev-parse", "--verify", f"refs/heads/{branch}")
        if rc == 0:
            branch_head = out
            lines.append("branch_exists_local: true")
            lines.append(f"branch_head: {branch_head}")
        else:
            lines.append("branch_exists_local: false")
            lines.append("branch_head: none")

    # -- worktree ---------------------------------------------------------
    worktree = state.get("worktree")
    lines.append(f"worktree: {worktree or 'none'}")
    if worktree:
        worktree_path = repo_root / worktree if not Path(worktree).is_absolute() else Path(worktree)
        if not worktree_path.is_dir():
            lines.append("worktree_state: absent")
        else:
            # `git -C` on a DIFFERENT worktree, read-only, from inside a single
            # helper -- the documented exception in CLAUDE.md.
            rc_head, head = _git(repo_root, "-C", str(worktree_path), "rev-parse", "HEAD")
            rc_branch, wt_branch = _git(
                repo_root, "-C", str(worktree_path), "rev-parse", "--abbrev-ref", "HEAD"
            )
            if rc_head != 0 or rc_branch != 0:
                lines.append("worktree_state: unusable")
                blocked = True
                blocker = (
                    f"Der Worktree {worktree_path} existiert, ist aber kein lesbarer "
                    "git-Worktree."
                )
            elif branch and wt_branch != branch:
                lines.append(f"worktree_head: {head}")
                lines.append(f"worktree_branch: {wt_branch}")
                lines.append("worktree_state: conflict")
                blocked = True
                blocker = (
                    f"Der Worktree {worktree_path} steht auf Branch '{wt_branch}', "
                    f"erwartet war '{branch}'. Nicht weiterarbeiten und nichts "
                    "loeschen -- der Worktree kann unfertige Arbeit enthalten."
                )
            else:
                lines.append(f"worktree_head: {head}")
                lines.append(f"worktree_branch: {wt_branch}")
                lines.append("worktree_state: reusable")

    # -- push -------------------------------------------------------------
    pushed_sha = state.get("pushed_sha")
    lines.append(f"recorded_pushed_sha: {pushed_sha or 'none'}")
    if not pushed_sha:
        push_state = "none"
    elif branch_head is None:
        push_state = "unknown"
    elif pushed_sha == branch_head:
        push_state = "current"
    else:
        push_state = "stale"
    lines.append(f"push_state: {push_state}")

    # -- CI ---------------------------------------------------------------
    ci_head_sha = state.get("ci_head_sha")
    lines.append(f"recorded_ci_head_sha: {ci_head_sha or 'none'}")
    lines.append(f"recorded_ci_run: {state.get('ci_run') or 'none'}")
    if not ci_head_sha:
        ci_state = "none"
    elif branch_head is None:
        ci_state = "unknown"
    elif ci_head_sha == branch_head:
        ci_state = "current"
    else:
        ci_state = "stale"
    lines.append(f"ci_state: {ci_state}")

    # -- pull request / merge --------------------------------------------
    lines.append(f"pr_number: {state.get('pr_number') or 'none'}")
    lines.append(f"merge_state: {state.get('merge_state') or 'unknown'}")

    # -- review rounds ----------------------------------------------------
    rounds = _review_rounds(repo_root, finding_id)
    lines.append(f"review_rounds: {len(rounds)}")
    if not rounds:
        lines.append("latest_review_result: none")
        lines.append("review_state: none")
    else:
        number, path = rounds[-1]
        result = _read_prefixed(path, REVIEW_RESULT_PREFIX)
        reviewed_hash = _read_prefixed(path, REVIEW_SCOPE_HASH_PREFIX)
        lines.append(f"latest_review_round: {number}")
        lines.append(f"latest_review_result: {result or 'unbekannt'}")
        lines.append(f"latest_review_scope_hash: {reviewed_hash or 'unbekannt'}")
        try:
            current_hash, _ = compute_scope_hash(repo_root)
        except ScopeHashError:
            current_hash = None
        lines.append(f"current_scope_hash: {current_hash or 'unbekannt'}")
        if current_hash is None or reviewed_hash is None:
            lines.append("review_state: unknown")
        elif reviewed_hash == current_hash:
            lines.append("review_state: current")
        else:
            lines.append("review_state: stale")

    lines.append(_next_step(state, push_state, ci_state, rounds, lines))
    return lines, blocked, blocker


def _next_step(state, push_state, ci_state, rounds, lines):
    """One deterministic sentence: what a resuming agent should do next."""
    if state.get("merge_state") == "merged":
        return "resume_next: bereits gemergt -- nichts weiter zu tun, Remote-Stand verifizieren."
    if push_state in ("none", "stale"):
        return (
            "resume_next: pushen (der zuletzt gepushte Stand ist nicht der aktuelle "
            "Branch-Head) -- danach CI-Evidence neu erheben."
        )
    if ci_state != "current":
        return "resume_next: required-check fuer den aktuellen Head-SHA erheben."
    review_line = next((line for line in lines if line.startswith("review_state:")), "")
    if review_line.endswith("current") and any(
        line == "latest_review_result: PASS" for line in lines
    ):
        return "resume_next: Closure-Felder setzen und mergen (Review deckt den aktuellen Stand)."
    if rounds:
        return "resume_next: neue Review-Runde noetig (kein gueltiges PASS fuer den aktuellen Stand)."
    return "resume_next: unabhaengigen Review anstossen."


def main(argv):
    parser = argparse.ArgumentParser(description="Resume state for one finding.")
    parser.add_argument("command", choices=["record", "show", "assess", "path"])
    parser.add_argument("finding_id")
    parser.add_argument("pairs", nargs="*")
    parser.add_argument("--repo-root", type=Path, default=DEFAULT_REPO_ROOT)
    args = parser.parse_args(argv[1:])

    repo_root = args.repo_root.resolve()

    try:
        if args.command == "path":
            print(state_path(repo_root, args.finding_id))
            return 0

        if args.command == "record":
            if not args.pairs:
                print("record braucht mindestens ein key=value-Paar.", file=sys.stderr)
                return 1
            state = record_state(repo_root, args.finding_id, args.pairs)
            for key in sorted(state):
                print(f"{key}: {state[key]}")
            return 0

        if args.command == "show":
            state = load_state(repo_root, args.finding_id)
            if not state:
                print("recorded_state: none")
                return 0
            for key in sorted(state):
                print(f"{key}: {state[key]}")
            return 0

        lines, blocked, blocker = assess(repo_root, args.finding_id)
    except StateError as exc:
        print(f"FINDING_STATE_ERROR: {exc}", file=sys.stderr)
        return 1

    for line in lines:
        print(line)

    if blocked:
        print(f"AUTONOMY_BLOCKER: {blocker}", file=sys.stderr)
        return 1
    return 0


if __name__ == "__main__":
    sys.exit(main(sys.argv))
