#!/usr/bin/env python3
"""Deterministic, LLM-free guard for factory build orders (audit finding F-10).

Usage:
    python3 factory/guards/validate-build-order.py <path-to-build-order.md>

Exit code 0 = the build order is valid for its finding's current status.
Exit code 1 = it is not; details are printed to stderr.

## Why this guard exists

The factory's whole review model rests on the build order. The independent
reviewer (.claude/agents/finding-closure-reviewer.md) is explicitly told NOT
to invent its own security framework, but to hold the build order against the
actual code: does the fix address the documented root cause, was the named
regression test really red before and green after, was the declared scope
respected. With no build order -- or with one whose sections are empty
headings -- that instruction has nothing to hold, and the reviewer silently
degrades into "does this look fine to me".

Before this guard, "ein Finding bekommt einen Bauauftrag" existed only as
prose in factory/build-orders/README.md. A finding could reach IMPLEMENTING,
VERIFYING, READY_FOR_CLOSURE and CLOSED with no build order at all, and every
layer -- validate-finding.py, the canonical runner, the Stop hook, GitHub CI
-- reported success. The factory must not require a build order in prose only;
that is the same "an assertion was checked instead of a binding" pattern the
trust-core package (F-01..F-09) removed everywhere else.

## What is checked

1.  **Canonical location.** The file's resolved real path is inside the
    resolved real factory/build-orders/ directory, and its name is
    <Finding-ID>.md. A symlink cannot lead out of that directory. README.md
    is not a build order and is never treated as one.
2.  **Mutual binding to a finding.** factory/findings/<Finding-ID>.md must
    exist, and the build order's title line must read
    `# Bauauftrag: <Finding-ID>` for that same ID. An orphan build order, or
    one titled for a different finding, is rejected -- the same identity
    binding F-02 established for review artifacts.
3.  **Required sections.** All of: Primäre Sicherheitsgrenze, Verbindliche
    Reihenfolge, Acceptance Criteria, Scope, Red Regression Evidence, Green
    Runtime Fix Evidence. Extra sections are allowed and ignored. Heading
    matching is umlaut- and case-insensitive so the template stays usable
    with either "Primäre" or "Primaere".
4.  **No placeholders.** Every required section must carry real content:
    non-empty, not one of the known placeholder tokens (TBD, TODO, N/A,
    "Not yet analyzed"), and not a token amount of text.
5.  **Evidence follows the lifecycle**, read from the finding's own Status:
      - from IMPLEMENTING onwards: Red Regression Evidence must quote actual
        output -- it must contain a non-empty fenced code block. "Der Test war
        rot" without the run is an assertion, not evidence.
      - from VERIFYING onwards: Green Runtime Fix Evidence must do the same.
    At IMPLEMENTING the green section may still be a note about what will be
    run; demanding it there would force the record to be written before it is
    true, which is exactly the habit this factory is built to prevent.

Statuses OPEN, ANALYZED and EXPERT_REVIEW_REQUIRED do not require a build
order at all: it is written after ANALYZED, and the escalation must stay
reachable from a state where no build order could exist yet. That check lives
in validate-finding.py; this guard is what runs once a build order is present.
"""
import re
import sys
from pathlib import Path

# Importing nothing from scope_hash here, but the same rule applies to every
# guard the factory runs repeatedly: leaving generated bytecode next to the
# source would become tracked content and move the scope hash (see
# validate-finding.py for the full explanation of that defect).
sys.dont_write_bytecode = True

sys.path.insert(0, str(Path(__file__).resolve().parent))
from finding_format import parse_finding  # noqa: E402

# factory/guards/validate-build-order.py -> parents[2] = repo root
REPO_ROOT = Path(__file__).resolve().parents[2]
BUILD_ORDERS_DIR = REPO_ROOT / "factory" / "build-orders"
FINDINGS_DIR = REPO_ROOT / "factory" / "findings"

# Files in factory/build-orders/ that are documentation, not build orders.
NON_BUILD_ORDER_NAMES = {"README.md"}

# No STATUS_LINE_RE here any more: the finding's status is read through
# finding_format.parse_finding (F-18), never by scanning this file's own text.
TITLE_RE = re.compile(r"^#\s*Bauauftrag:\s*(.+?)\s*$")
SECTION_HEADING_RE = re.compile(r"^##\s+(.*?)\s*$")
ANY_TOP_HEADING_RE = re.compile(r"^#{1,2}\s")
FENCE_RE = re.compile(r"^\s*```")

PLACEHOLDER_VALUES = {
    "",
    "tbd",
    "todo",
    "not yet analyzed",
    "n/a",
    "noch offen",
    "steht noch aus",
}

# Minimum amount of real (non-whitespace) content a section must carry. This
# is deliberately small: the guard's job is to reject empty shells, not to
# grade prose.
MIN_SECTION_CHARS = 40

# Canonical section name -> normalized lookup key.
REQUIRED_SECTIONS = (
    "Primäre Sicherheitsgrenze",
    "Verbindliche Reihenfolge",
    "Acceptance Criteria",
    "Scope",
    "Red Regression Evidence",
    "Green Runtime Fix Evidence",
)

RED_EVIDENCE_SECTION = "Red Regression Evidence"
GREEN_EVIDENCE_SECTION = "Green Runtime Fix Evidence"

# Statuses at which a build order must exist at all. Kept here (rather than
# only in validate-finding.py) so both sides read the same list.
STATUSES_REQUIRING_BUILD_ORDER = {
    "IMPLEMENTING",
    "VERIFYING",
    "READY_FOR_CLOSURE",
    "CLOSED",
}

STATUSES_REQUIRING_RED_EVIDENCE = STATUSES_REQUIRING_BUILD_ORDER
STATUSES_REQUIRING_GREEN_EVIDENCE = {"VERIFYING", "READY_FOR_CLOSURE", "CLOSED"}

_UMLAUT_MAP = {
    "ä": "ae",
    "ö": "oe",
    "ü": "ue",
    "ß": "ss",
    "Ä": "ae",
    "Ö": "oe",
    "Ü": "ue",
}


def normalize_heading(text):
    """Lower-case, umlaut-folded, whitespace-collapsed heading key."""
    folded = "".join(_UMLAUT_MAP.get(char, char) for char in text)
    return re.sub(r"\s+", " ", folded.strip().lower())


def parse_sections(text):
    """Return {normalized heading: body text} for every '## ' section."""
    sections = {}
    current_key = None
    current_body = []

    for raw_line in text.splitlines():
        heading_match = SECTION_HEADING_RE.match(raw_line)
        if heading_match:
            if current_key is not None:
                sections[current_key] = "\n".join(current_body)
            current_key = normalize_heading(heading_match.group(1))
            current_body = []
            continue
        if current_key is not None and ANY_TOP_HEADING_RE.match(raw_line):
            # A '# ' heading ends the current section without opening a new one.
            sections[current_key] = "\n".join(current_body)
            current_key = None
            current_body = []
            continue
        if current_key is not None:
            current_body.append(raw_line)

    if current_key is not None:
        sections[current_key] = "\n".join(current_body)
    return sections


def read_title_id(text):
    """The finding ID named by the '# Bauauftrag: <ID>' title, or None."""
    for raw_line in text.splitlines():
        if not raw_line.strip():
            continue
        match = TITLE_RE.match(raw_line.strip())
        if match:
            return match.group(1).strip()
        if raw_line.lstrip().startswith("#"):
            return None
    return None


def read_finding_status(finding_path):
    """The finding's Status value, or None if it has none.

    Read through finding_format, the single canonical finding parser (audit
    finding F-18). This function used to scan the whole document for the first
    `Status:` line, which meant a quoted ticket or log excerpt could set the
    status the evidence lifecycle below depends on -- a finding at VERIFYING
    could be read as OPEN and escape the requirement to quote a green run.
    """
    text = finding_path.read_text(encoding="utf-8")
    status = parse_finding(text)["status"]
    return status.strip().upper() if status else None


def has_quoted_output(body):
    """True if the section contains a fenced block with real content.

    Evidence sections must quote what actually ran. A sentence claiming a red
    or green run is exactly the unbacked assertion this factory rejects
    everywhere else.
    """
    inside = False
    content_lines = 0
    for raw_line in body.splitlines():
        if FENCE_RE.match(raw_line):
            if inside:
                if content_lines > 0:
                    return True
                inside = False
                content_lines = 0
            else:
                inside = True
                content_lines = 0
            continue
        if inside and raw_line.strip():
            content_lines += 1
    return False


def _section_problems(name, body):
    """Placeholder/substance problems for one required section."""
    problems = []
    stripped = (body or "").strip()
    if not stripped:
        problems.append(f"Abschnitt '{name}' ist leer.")
        return problems

    if stripped.strip(" .").lower() in PLACEHOLDER_VALUES:
        problems.append(f"Abschnitt '{name}' ist ein Platzhalter ('{stripped.strip()}').")
        return problems

    substantive = "".join(stripped.split())
    if len(substantive) < MIN_SECTION_CHARS:
        problems.append(
            f"Abschnitt '{name}' hat zu wenig Inhalt ({len(substantive)} Zeichen) "
            "und ist damit ein Platzhalter, kein Bauauftragsabschnitt."
        )
    return problems


def validate_build_order(path, repo_root=REPO_ROOT):
    """Return a list of human-readable error strings; empty list means valid."""
    errors = []
    build_orders_dir = repo_root / "factory" / "build-orders"
    findings_dir = repo_root / "factory" / "findings"

    # 1. canonical location -- resolved, so a symlink cannot lead out
    try:
        resolved_dir = build_orders_dir.resolve(strict=True)
        resolved_path = path.resolve(strict=True)
    except (OSError, RuntimeError):
        return [
            f"Bauauftrag '{path}' ist nicht aufloesbar oder "
            f"'{build_orders_dir}' existiert nicht."
        ]

    if resolved_dir != resolved_path.parent:
        return [
            f"Bauauftrag '{path}' liegt nach Aufloesung in '{resolved_path.parent}' "
            f"und damit nicht im kanonischen Verzeichnis 'factory/build-orders'."
        ]

    if resolved_path.name in NON_BUILD_ORDER_NAMES:
        return [f"'{resolved_path.name}' ist Dokumentation, kein Bauauftrag."]

    if resolved_path.suffix != ".md":
        return [f"Bauauftrag '{resolved_path.name}' ist keine .md-Datei."]

    finding_id = resolved_path.stem

    # 2. mutual binding: the finding must exist, the title must name it
    finding_path = findings_dir / f"{finding_id}.md"
    if not finding_path.is_file():
        return [
            f"Bauauftrag '{resolved_path.name}' hat kein zugehoeriges Finding: "
            f"'factory/findings/{finding_id}.md' existiert nicht. Ein Bauauftrag "
            "ohne Finding beschreibt Arbeit, die kein Befund angefordert hat."
        ]

    text = resolved_path.read_text(encoding="utf-8")

    title_id = read_title_id(text)
    if title_id is None:
        errors.append(
            f"Bauauftrag '{resolved_path.name}' hat keine Titelzeile "
            f"'# Bauauftrag: {finding_id}'."
        )
    elif title_id != finding_id:
        errors.append(
            f"Bauauftrag '{resolved_path.name}' ist laut Titelzeile fuer '{title_id}', "
            f"liegt aber unter dem Dateinamen '{finding_id}'. Finding-ID, Dateiname "
            "und Titel muessen dasselbe Finding benennen."
        )

    # 3./4. required sections, filled in
    sections = parse_sections(text)
    for name in REQUIRED_SECTIONS:
        key = normalize_heading(name)
        if key not in sections:
            errors.append(
                f"Pflichtabschnitt fehlt: '## {name}'. Siehe "
                "factory/build-orders/README.md fuer die verbindliche Gliederung."
            )
            continue
        errors.extend(_section_problems(name, sections[key]))

    # 5. evidence per lifecycle
    status = read_finding_status(finding_path)
    if status is None:
        errors.append(
            f"Finding '{finding_id}' hat kein 'Status:'-Feld -- ohne Status ist nicht "
            "bestimmbar, welche Evidence der Bauauftrag bereits tragen muss."
        )
        return errors

    for section_name, required_statuses in (
        (RED_EVIDENCE_SECTION, STATUSES_REQUIRING_RED_EVIDENCE),
        (GREEN_EVIDENCE_SECTION, STATUSES_REQUIRING_GREEN_EVIDENCE),
    ):
        if status not in required_statuses:
            continue
        key = normalize_heading(section_name)
        body = sections.get(key)
        if body is None:
            continue  # already reported as a missing section
        if _section_problems(section_name, body):
            continue  # already reported as empty/placeholder
        if not has_quoted_output(body):
            errors.append(
                f"Abschnitt '{section_name}' enthaelt keinen zitierten Lauf "
                "(kein nicht-leerer ```-Block). Bei Status "
                f"'{status}' ist die tatsaechliche Ausgabe Pflicht -- eine Behauptung, "
                "dass der Test rot bzw. gruen war, ist keine Evidence."
            )

    return errors


def main(argv):
    if len(argv) != 2:
        print("Usage: validate-build-order.py <path-to-build-order.md>", file=sys.stderr)
        return 1

    path = Path(argv[1])
    if not path.is_file():
        print(f"Datei nicht gefunden: {path}", file=sys.stderr)
        return 1

    errors = validate_build_order(path)

    if errors:
        print(f"UNGÜLTIG: {path}", file=sys.stderr)
        for error in errors:
            print(f"  - {error}", file=sys.stderr)
        return 1

    print(f"GÜLTIG: {path}")
    return 0


if __name__ == "__main__":
    sys.exit(main(sys.argv))
